const TRIP_REQUEST_CREATED = 1;
const TRIP_REQUEST_ACCEPTED = 2;
const TRIP_REQUEST_REJECTED = 3;
const TRIP_REQUEST_CANCEL = 4;
const TRIP_CANCEL = 5;
const CTO = 6;
const RTO = 7;
const TTO = 8;


export {TRIP_REQUEST_CREATED,TRIP_REQUEST_ACCEPTED,TRIP_REQUEST_REJECTED,TRIP_REQUEST_CANCEL,TRIP_CANCEL,CTO,RTO,TTO};