const WAITING_TRIP_TYPE = 1;
const RECEIVED_REQUEST_TRIP_TYPE = 2;
const SENT_REQUEST_TRIP_TYPE = 3;
const PAIRING_TRIP_TYPE = 4;
const OLD_TRIP_TYPE = 5;

export {WAITING_TRIP_TYPE,RECEIVED_REQUEST_TRIP_TYPE,SENT_REQUEST_TRIP_TYPE,PAIRING_TRIP_TYPE,OLD_TRIP_TYPE};